name: planik
description: Planik flutter application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: "2.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.4

  flutter_lints: 1.0.4
  # https://pub.dev/packages/uuid
  uuid: 3.0.5
  # https://pub.dev/packages/fpdart
  fpdart: 0.0.14
  # https://pub.dev/packages/shared_preferences
  shared_preferences: 2.0.13
  # https://pub.dev/packages/floor
  floor: 1.2.0
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: 8.0.1
  # https://pub.dev/packages/bloc_concurrency
  bloc_concurrency: 0.2.0
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: 0.15.0
  # https://pub.dev/packages/get_it
  get_it: 7.2.0
  # https://pub.dev/packages/adaptive_theme
  adaptive_theme: 2.3.0
  # https://pub.dev/packages/google_fonts
  google_fonts: ^2.3.1
  # https://pub.dev/packages/intl
  intl: 0.17.0
  # https://pub.dev/packages/flutter_sticky_header
  flutter_sticky_header: 0.6.0
  # https://pub.dev/packages/proxy_layout
  proxy_layout: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/floor_generator
  floor_generator: 1.2.0
  # https://pub.dev/packages/analyzer
  analyzer: 2.5.0
  # https://pub.dev/packages/bloc_test
  bloc_test: 9.0.2
  # https://pub.dev/packages/build_runner
  build_runner: 2.1.7
  # https://pub.dev/packages/freezed
  freezed: 0.15.0+1
  # https://pub.dev/packages/mocktail
  mocktail: 0.2.0

flutter:
  uses-material-design: true